[build]
command = "pip install --user -r requirements.txt"
publish = "."
functions = "netlify/functions"

[build.environment]
PYTHON_VERSION = "3.9"

[[redirects]]
from = "/*"
to = "/.netlify/functions/app"
status = 200

[functions]
node_bundler = "esbuild"
